CREATE TABLE PASSWORDS(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	VALOR VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ROLES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE USUARIOS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE_USUARIO VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(75) NOT NULL,
	PASSWORD_ID BIGINT NOT NULL,
	FECHA_CREACION TIMESTAMP NOT NULL,
	NOMBRE_COMPLETO VARCHAR(255),
	PRIMARY KEY(ID)
);
CREATE TABLE ROLES_USUARIOS(
	USUARIO_ID BIGINT NOT NULL,
	ROL_ID BIGINT NOT NULL,
	PRIMARY KEY(USUARIO_ID, ROL_ID)
);

ALTER TABLE USUARIOS ADD CONSTRAINT USU$PAS FOREIGN KEY(PASSWORD_ID) REFERENCES PASSWORDS(ID);
ALTER TABLE ROLES_USUARIOS ADD CONSTRAINT ROL_USU$ROL FOREIGN KEY (ROL_ID) REFERENCES ROLES(ID);
ALTER TABLE ROLES_USUARIOS ADD CONSTRAINT ROL_USU$USU FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID);

CREATE TABLE TIPOS_DE_CLIENTES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)
);


CREATE TABLE CLIENTES(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE_EMPRESA VARCHAR(100) NOT NULL,
    TIPO_DE_CLIENTE_ID BIGINT NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE CLIENTES ADD CONSTRAINT CLI$TIP FOREIGN KEY(TIPO_DE_CLIENTE_ID) REFERENCES TIPOS_DE_CLIENTES(ID);
ALTER TABLE CLIENTES ADD CONSTRAINT CLI$USU FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID);


CREATE TABLE NOTAS_TEXTO (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CONTENIDO TEXT(65535),
	PRIMARY KEY(ID)
);


CREATE TABLE MUESTRAS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	CODIGO_MUESTRA VARCHAR(100) NOT NULL,
	FECHA_INGRESO TIMESTAMP,
	FECHA_SALIDA TIMESTAMP,
	CLIENTE_ID BIGINT NOT NULL,
	NOTA_TEXTO_ID BIGINT NOT NULL,
	ESTADO_ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE ESTADOS(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE MUESTRAS ADD CONSTRAINT MUE$EST FOREIGN KEY(ESTADO_ID) REFERENCES ESTADOS(ID);
ALTER TABLE MUESTRAS ADD CONSTRAINT MUE$CLI FOREIGN KEY(CLIENTE_ID) REFERENCES CLIENTES(ID);
ALTER TABLE MUESTRAS ADD CONSTRAINT MUE$NOTA FOREIGN KEY(NOTA_TEXTO_ID) REFERENCES NOTAS_TEXTO(ID);




CREATE TABLE ENSAYOS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	FECHA_EJECUCION TIMESTAMP NOT NULL,
	EQUIPO_USADO VARCHAR(100),
	USUARIO_ID BIGINT NOT NULL,
	NOTA_TEXTO_ID BIGINT,
	MUESTRA_ID BIGINT NOT NULL,
	TIPO_DE_ENSAYO VARCHAR(100),
	PRIMARY KEY(ID)
);

ALTER TABLE ENSAYOS ADD CONSTRAINT ENS$USU FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID);
ALTER TABLE ENSAYOS ADD CONSTRAINT ENS$NOTA FOREIGN KEY(NOTA_TEXTO_ID) REFERENCES NOTAS_TEXTO(ID);
ALTER TABLE ENSAYOS ADD CONSTRAINT ENS$MUE FOREIGN KEY(MUESTRA_ID) REFERENCES MUESTRAS(ID);

CREATE TABLE RESULTADOS (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	PARAMETRO VARCHAR(100) NOT NULL,
	UNIDAD VARCHAR(50) NOT NULL,
	VALOR_OBTENIDO DOUBLE NOT NULL,
	CUMPLE TINYINT NOT NULL,
	VALOR_MAXIMO DOUBLE,
	VALOR_MINIMO DOUBLE,
	NOTA_TEXTO_ID BIGINT,
	ENSAYO_ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE RESULTADOS ADD CONSTRAINT RES$NOT FOREIGN KEY(NOTA_TEXTO_ID) REFERENCES NOTAS_TEXTO(ID);
ALTER TABLE RESULTADOS ADD CONSTRAINT RES$ENS FOREIGN KEY(ENSAYO_ID) REFERENCES ENSAYOS(ID);

CREATE TABLE IMAGENES (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(100) NOT NULL,
	CONTENT_TYPE VARCHAR(100),
	CONTENIDO MEDIUMBLOB NOT NULL,
	RESULTADO_ID BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

ALTER TABLE IMAGENES ADD CONSTRAINT IMG$RES FOREIGN KEY(RESULTADO_ID) REFERENCES RESULTADOS(ID);




CREATE TABLE VALIDACIONES(
	ID BIGINT NOT NULL AUTO_INCREMENT,
	APROBADO TINYINT NOT NULL,
	FECHA_FIRMA TIMESTAMP NOT NULL,
	USUARIO_ID BIGINT NOT NULL,
	RESULTADO_ID BIGINT NOT NULL,
	NOTA_TEXTO_ID BIGINT,
	PRIMARY KEY(ID)
);

ALTER TABLE VALIDACIONES ADD CONSTRAINT VAL$USU FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID);
ALTER TABLE VALIDACIONES ADD CONSTRAINT VAL$RES FOREIGN KEY(RESULTADO_ID) REFERENCES RESULTADOS(ID);
ALTER TABLE VALIDACIONES ADD CONSTRAINT VAL$NOT FOREIGN KEY(NOTA_TEXTO_ID) REFERENCES NOTAS_TEXTO(ID);

