ALTER TABLE VALIDACIONES DROP CONSTRAINT VAL$USU;

ALTER TABLE VALIDACIONES DROP CONSTRAINT VAL$RES;

ALTER TABLE VALIDACIONES DROP CONSTRAINT VAL$NOT;

DROP TABLE VALIDACIONES;

ALTER TABLE IMAGENES DROP CONSTRAINT IMG$RES; 

DROP TABLE IMAGENES;

ALTER TABLE RESULTADOS DROP CONSTRAINT RES$ENS;

ALTER TABLE RESULTADOS DROP CONSTRAINT RES$NOT;

DROP TABLE RESULTADOS;

ALTER TABLE ENSAYOS DROP CONSTRAINT ENS$MUE;

ALTER TABLE ENSAYOS DROP CONSTRAINT ENS$NOTA;

ALTER TABLE ENSAYOS DROP CONSTRAINT ENS$USU;

ALTER TABLE ENSAYOS DROP CONSTRAINT ENS$EST

DROP TABLE ENSAYOS;

ALTER TABLE MUESTRAS DROP CONSTRAINT MUE$NOTA; 

ALTER TABLE MUESTRAS DROP CONSTRAINT MUE$CLI;

ALTER TABLE MUESTRAS DROP CONSTRAINT MUE$EST;

DROP TABLE ESTADOS;

DROP TABLE MUESTRAS;

DROP TABLE NOTAS_TEXTO;

ALTER TABLE CLIENTES DROP CONSTRAINT CLI$USU;

ALTER TABLE CLIENTES DROP CONSTRAINT CLI$TIP;

DROP TABLE CLIENTES;

DROP TABLE TIPOS_DE_CLIENTES;

ALTER TABLE ROLES_USUARIOS DROP CONSTRAINT ROL_USU$USU;

ALTER TABLE ROLES_USUARIOS DROP CONSTRAINT ROL_USU$ROL;

ALTER TABLE USUARIOS DROP CONSTRAINT USU$PAS;

DROP TABLE ROLES_USUARIOS;

DROP TABLE USUARIOS;

DROP TABLE ROLES;

DROP TABLE PASSWORDS;