
INSERT INTO ESTADOS (ID,NOMBRE) values (0,'RECIBIDO');
INSERT INTO ESTADOS (ID,NOMBRE) values (1,'EN ANALISIS');
INSERT INTO ESTADOS (ID,NOMBRE) values (2,'COMPLETADO');
INSERT INTO ESTADOS (ID,NOMBRE) values (3,'POR VALIDAR');
INSERT INTO ESTADOS (ID,NOMBRE) values (4,'APROBADO');
INSERT INTO ESTADOS (ID,NOMBRE) values (5,'RECHAZADO');

